version: '3'

services:
  service1:
    build:
      context: ./service_1
    container_name: service1
    expose:
      - "8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  service2:
    build:
      context: ./service_2
    container_name: service2
    expose:
      - "8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
